/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: nitwit.friends (https://sketchfab.com/nitwit.friends)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/deadpool-dancing-0257cc47a19f46cd9f1e7dbf61b18dd7
Title: Deadpool Dancing
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import deadpool_dancing from '../assets/3d/deadpool_dancing.glb'

export function DeadpoolDancing(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF(deadpool_dancing)
  const { actions, names } = useAnimations(animations, group)

  useEffect(() => {
    // Get all animation names
    console.log('Available animations:', names)
    
    // Play all animations
    if (actions) {
      Object.values(actions).forEach((action) => {
        if (action) {
          action
            .reset()
            .setEffectiveTimeScale(1)
            .setEffectiveWeight(1)
            .fadeIn(0.5)
            .play()
        }
      })
    }
  }, [actions, names])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={0.003}>
          <group name="fbx_mergefbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Object_4">
                  <primitive object={nodes._rootJoint} />
                  <skinnedMesh
                    name="Object_7"
                    geometry={nodes.Object_7.geometry}
                    material={materials.Cobura}
                    skeleton={nodes.Object_7.skeleton}
                    castShadow
                    receiveShadow
                  />
                  <skinnedMesh
                    name="Object_8"
                    geometry={nodes.Object_8.geometry}
                    material={materials.material}
                    skeleton={nodes.Object_8.skeleton}
                    castShadow
                    receiveShadow
                  />
                  <skinnedMesh
                    name="Object_9"
                    geometry={nodes.Object_9.geometry}
                    material={materials.Sword}
                    skeleton={nodes.Object_9.skeleton}
                    castShadow
                    receiveShadow
                  />
                  <skinnedMesh
                    name="Object_10"
                    geometry={nodes.Object_10.geometry}
                    material={materials.material_3}
                    skeleton={nodes.Object_10.skeleton}
                    castShadow
                    receiveShadow
                  />
                  <skinnedMesh
                    name="Object_11"
                    geometry={nodes.Object_11.geometry}
                    material={materials.Knife}
                    skeleton={nodes.Object_11.skeleton}
                    castShadow
                    receiveShadow
                  />
                  <skinnedMesh
                    name="Object_12"
                    geometry={nodes.Object_12.geometry}
                    material={materials.Knifel_Belt}
                    skeleton={nodes.Object_12.skeleton}
                    castShadow
                    receiveShadow
                  />
                  <skinnedMesh
                    name="Object_13"
                    geometry={nodes.Object_13.geometry}
                    material={materials.Belt_foot}
                    skeleton={nodes.Object_13.skeleton}
                    castShadow
                    receiveShadow
                  />
                  <skinnedMesh
                    name="Object_14"
                    geometry={nodes.Object_14.geometry}
                    material={materials.Back}
                    skeleton={nodes.Object_14.skeleton}
                    castShadow
                    receiveShadow
                  />
                  <skinnedMesh
                    name="Object_15"
                    geometry={nodes.Object_15.geometry}
                    material={materials.Body}
                    skeleton={nodes.Object_15.skeleton}
                    castShadow
                    receiveShadow
                  />
                  <skinnedMesh
                    name="Object_16"
                    geometry={nodes.Object_16.geometry}
                    material={materials.Belt}
                    skeleton={nodes.Object_16.skeleton}
                    castShadow
                    receiveShadow
                  />
                  <group name="Object_6" position={[0, 0, 0]} />
                  <group name="Mesh" position={[0, 0, 0]}>
                    <group name="Cobura_L_1_1" position={[0, 0, 0]} />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload(deadpool_dancing)
export default deadpool_dancing
