/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Vetech82 (https://sketchfab.com/Vetech82)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/flying-icarus-animated-486dd990a5bc49a68e9ae1d1f103aedc
Title: Flying Icarus - animated
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import flying_icarus_animated from "../assets/3d/flying_icarus_-_animated.glb";

export function FlyingIcarus(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF(flying_icarus_animated)
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    // Play the first animation
    if (actions && Object.keys(actions).length > 0) {
      const action = actions[Object.keys(actions)[0]]
      action.play()
    }
  }, [actions])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="metarig_249" position={[0, -1.882, -0.35]} scale={5.148}>
                <group name="GLTF_created_4">
                  <primitive object={nodes.GLTF_created_4_rootJoint} />
                  <skinnedMesh
                    name="Object_7"
                    geometry={nodes.Object_7.geometry}
                    material={materials.TT_checker_2048x2048_UV_GRID}
                    skeleton={nodes.Object_7.skeleton}
                  />
                  <group name="telo_low_248" />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

export default FlyingIcarus;
useGLTF.preload(flying_icarus_animated)
