/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Walter Araujo (https://sketchfab.com/walteraraujo)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/robot-hip-hop-dancing-bedd2ba99e1840ff89d2bca4a3e0c276
Title: Robot Hip Hop Dancing
*/

import React, { useRef, useEffect, useState } from 'react'
import { useGLTF, useAnimations, useTexture } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import * as THREE from 'three'
import robot_hip_hop_dancing from '../assets/3d/robot_hip_hop_dancing.glb'

export function RobotHipHopDancing(props) {
  const group = useRef()
  const [isLoading, setIsLoading] = useState(true)
  const [error, setError] = useState(null)

  try {
    const { nodes, materials, animations } = useGLTF(robot_hip_hop_dancing)
    const { actions } = useAnimations(animations, group)

    useEffect(() => {
      console.log("Robot model loaded:", { nodes, materials, animations })
      const initializeAnimation = async () => {
        try {
          setIsLoading(true)
          if (actions && Object.keys(actions).length > 0) {
            const action = actions[Object.keys(actions)[0]]
            if (action) {
              console.log("Playing robot animation")
              action.reset()
                .setEffectiveTimeScale(1)
                .setEffectiveWeight(1)
                .fadeIn(0.5)
                .play()
              
              action.setLoop(THREE.LoopRepeat, Infinity)
              action.timeScale = 0.8 + Math.random() * 0.4
            }
          }
        } catch (error) {
          console.error('Error initializing robot animation:', error)
          setError(error)
        } finally {
          setIsLoading(false)
        }
      }

      initializeAnimation()

      return () => {
        if (actions) {
          Object.values(actions).forEach(action => {
            if (action) {
              action.fadeOut(0.5)
            }
          })
        }
      }
    }, [actions])

    useFrame((state) => {
      if (group.current) {
        group.current.position.y = Math.sin(state.clock.elapsedTime * 0.5) * 0.1
        group.current.rotation.y = Math.sin(state.clock.elapsedTime * 0.2) * 0.1
      }
    })

    if (isLoading) {
      return null
    }

    if (error) {
      console.error("Robot model error:", error)
      return null
    }

    return (
      <group ref={group} {...props} dispose={null}>
        <group name="Sketchfab_Scene">
          <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={0.1}>
            <group
              name="a5d523f9129a4a26bb34c75153857384fbx"
              rotation={[Math.PI / 2, 0, 0]}
              scale={0.01}>
              <group name="Object_2">
                <group name="RootNode">
                  <group name="Object_4">
                    <primitive object={nodes._rootJoint} />
                    <skinnedMesh
                      name="Object_7"
                      geometry={nodes.Object_7.geometry}
                      material={materials.mat0mat}
                      skeleton={nodes.Object_7.skeleton}
                      castShadow
                      receiveShadow
                    >
                      <meshStandardMaterial
                        {...materials.mat0mat}
                        metalness={0.8}
                        roughness={0.2}
                        envMapIntensity={1}
                      />
                    </skinnedMesh>
                    <group name="Object_6" />
                    <group name="unamed" />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    )
  } catch (error) {
    console.error("Error loading robot model:", error)
    return null
  }
}

useGLTF.preload(robot_hip_hop_dancing)
export default robot_hip_hop_dancing
